# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 828420a2f118dd79c8ca7802a3d380b154244331bd1e903f8c09e9466f77b1acacf39c2c8a25d40b50af598c127fc8d95978de2ac1fdf4915741bcf4f0a7af5c

test:
  secret_key_base: 7eef3d34afe07ee62ec0bbff3f571fddf23f1a2d2b4f52546d3bc7e05083ea85deb21414132dbd58330a6bb35b30c6cc144782663645626c1b02848421e53bc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
